package com.arjit.datastructure.string;

/*Given a string return all possible subsequences which start with vowel and end with consonant. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples:

Input : 'abc'
Output : ab, ac, abc

Input : 'aab'
Output : ab, aab*/
public class StringSubsequence {

	static void printsubSequence(String input) {
		char ch[] = input.toCharArray();
		int start, end;
		for(int i = 0; i < ch.length; i++) {
		}
	}
	
	public static void main(String[] args) {
		printsubSequence("aab");
	}

}
